#ifndef LAB_07_STRUCTCLASS_PROGRAMCOUNTIRESPOPULATION_H
#define LAB_07_STRUCTCLASS_PROGRAMCOUNTIRESPOPULATION_H

class ProgramCountriesPopulation {
public:
    static int main();
};

#endif //LAB_07_STRUCTCLASS_PROGRAMCOUNTIRESPOPULATION_H